const data = {
  products: [
    {
      _id: "1",
      name: "Sumsung-Galaxy-s22",
      slug: "Sumsung-Galaxy-s22",
      category: "phones",
      image: "/images/p1.jpg",//800 px
      price: 799.99,
      countInstock: 20,
      brand: "Sumsung",
      rating: 4.5,
      numReviews: 50,
      description: "Hight Quality Product",
    },
    {
      _id: "2",
      name: "iphone 13",
      slug: "iphone 13",
      category: "phones",
      image: "/images/p2.jpg",
      price:899,
      countInstock: 0,
      brand: "apple",
      rating: 4.0,
      numReviews: 60,
      description: "Hight Quality Product",
    },
    {
      _id: "3",
      name: "iphone 12",
      slug: "iphone 12",
      category: "phones",
      image: "/images/p3.jpg",
      price: 799,
      countInstock: 40,
      brand: "apple",
      rating: 4.5,
      numReviews: 70,
      description: "Hight Quality Product",
    },
    {
      _id: "4",
      name: "oppo reno 6",
      slug: "oppo reno 6",
      category: "phones",
      image: "/images/p4.jpg",
      price: 410,
      countInstock: 50,
      brand: "oppo",
      rating: 4.5,
      numReviews: 40,
      description: "Hight Quality Product",
    },
  ],
};

export default data;
