const data = {
  products: [
    {
      _id: "1",
      name: "nike slim shirt",
      slug: "nike-slim-shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 250,
      countInstock: 20,
      brand: "nike",
      rating: 1.0,
      numReviews: 10,
      description: "Hight Quality Product",
    },
    {
      _id: "2",
      name: "adida slim shirt",
      slug: "adidas-slim-shirt",
      category: "adidas",
      image: "/images/p2.jpg",
      price: 150,
      countInstock: 0,
      brand: "Adidas",
      rating: 2.0,
      numReviews: 10,
      description: "Hight Quality Product",
    },
    {
      _id: "3",
      name: "nike slim pants",
      slug: "nike-slim-pants",
      category: "pants",
      image: "/images/p3.jpg",
      price: 250,
      countInstock: 40,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 60,
      description: "Hight Quality Product",
    },
    {
      _id: "4",
      name: "adidas slim pants",
      slug: "adidas-slim-pants",
      category: "pants",
      image: "/images/p4.jpg",
      price: 350,
      countInstock: 50,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 70,
      description: "Hight Quality Product",
    },
  ],
};

export default data;
